---
title: "19 Тепловой насос"
author: "Бутылов Матвей (21Б07)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document:
    extra_dependencies:
      fontenc:
      - T1
      - T2A
      inputenc: utf8
      babel:
      - english
      - russian
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

измерения проводились 29.03.2022

**Цель работы:**

Изучить принцип работы теплового насоса:

-   Рассчитать зависимость эффективности работы теплового насоса от изменения температуры, построить соответствующий график;

-   Оценить суммарную энергию тепловых потерь, полезную работу компрессора, сравнить полученные значения с общей потребленной энергией;

-   Найти КПД компрессора.

Изучить принцип работы расширительного клапана:

-   Построить графики зависимости температуры на выходе из испарителя, на входе в испаритель и температуры перегрева от времени;

-   Определить температуру перегрева в стационарном режиме работы теплового насоса;

-   Оценить время выхода установки на стационарный режим работы после включения.

**В работе используются:** Холодный резервуар, горячий резервуар, компрессор, расширительный клапан, цифровой термометр, ваттметр.

# Формулы

Введем переменные

$\varepsilon$ -- эффективность насоса $Т_1$ -- температура холодного резервуара $Т_2$ -- температура горячего резервуара $С$ -- теплоемкость воды (4, 187 кДж/Кг\*К) $m$ -- масса резервуара с водой (4Кг) $t$ -- время $Q_1$ -- количество теплоты забранное из первого резервуара $Q_2$ -- количество теплоты полученное вторым резервуаром $W_{потр}$ -- энергия, потребляемая из энергосети $W_{потерь}$ -- тепловые потери $P$ -- мощность потребляемая установкой $W_{полезн}$ -- работа компрессора $η$ -- КПД компрессора $Т_{вых}$ -- температура на выходе из испарителя $Т_{вых}$ -- температура на входе в испаритель


Тогда эффективность теплового насоса выражается как $\varepsilon=\frac{\Delta T_{2}}{P \Delta t} C m$
Энергия тепловых потерь  как $\mathrm{W}_{\text {потерь }}=W_{\text {потр }}+\left|Q_{1}\right|-\left|Q_{2}\right|=Pt+\left|Q_{1}\right|-\left|Q_{2}\right|$


